import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'

import '@/styles/globals.css'

const nunito = Nunito({
  subsets: ['latin'],
  weight: ['400', '700', '900']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='es'>
      <body className={`${nunito.className} antialiased`}>{children}</body>
    </html>
  )
}
